name: Deploy Bicep file
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Create RG
      uses: azure/powershell@v2
      with:
        inlineScript: 
        azPSVersion: "latest"

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v2
      id: deploy
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./deploy.bicep
        parameters: ./deploy.bicepparam
        failOnStdErr: false
    
    - run: echo ${{ steps.deploy.outputs.minecraftServerAddress}} 
