name: Deploy Bicep file
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Create RG
      id: rg
      uses: azure/powershell@v2
      env:
        POWERSHELL_TELEMETRY_OUTPUT: 1
      with:
        inlineScript: |
          $RGroupName = "rg-uks-sandbox-github-actions-paulmc"
          $RGroupLocation = "UK South"
          $ResourceGroupTags = @{
          "Created By" = "Paul McCormack"; 
          "Environment" = "Training";
          "Service" = "Training";
          "Management Area" = "DDaT";
          "Recharge" = "DDaT";
          }
          Set-AzContext -SubscriptionId ${{secrets.AZURE_SUBSCRIPTION}}
          New-AzResourceGroup -Name $RGroupName -Location $RGroupLocation -Tag $ResourceGroupTags
          Write-Output "rgName=$($RGroupName)" >> $Env:GITHUB_OUTPUT
        azPSVersion: "latest"

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v2
      id: deploy
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ steps.rg.outputs.rgName }}
        template: ./deploy.bicep
        parameters: ./deploy.bicepparam
        failOnStdErr: false
    
    - run: echo ${{ steps.deploy.outputs.minecraftServerAddress }} 
